# YAML Lint configuration
# Documentation: https://yamllint.readthedocs.io/

extends: default

rules:
  line-length:
    max: 120
    level: warning

  comments:
    min-spaces-from-content: 2

  comments-indentation: disable

  document-start: disable

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

  indentation:
    spaces: 2
    indent-sequences: true

  brackets:
    max-spaces-inside: 1

  braces:
    max-spaces-inside: 1
