name: Super-Linter

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for better analysis

      - name: Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Linter on/off switches
          VALIDATE_ALL_CODEBASE: false  # Only lint changed files on PRs
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_BASH: true
          VALIDATE_ENV: true
          VALIDATE_GITHUB_ACTIONS: true
          
          # TypeScript/JavaScript specific
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          
          # Prettier for formatting checks
          VALIDATE_PRETTIER: true
          PRETTIER_CONFIG_FILE: .prettierrc
          
          # File filters
          FILTER_REGEX_EXCLUDE: .*dist/.*|.*node_modules/.*|.*coverage/.*
          
          # Output
          LINTER_RULES_PATH: /
          LOG_LEVEL: INFO
          CREATE_LOG_FILE: false
          
          # Behavior
          DISABLE_ERRORS: false  # Set to true for warnings only
          MULTI_STATUS: true     # Post individual status for each linter